
/*
 * @file version.h
 *
 * @brief Auto generated identity macros. 
 * This file is generated by scripts/gen_version.py and should not be modified manually. 
 * Manual edits will be overwritten by the next build.
 */

#ifndef VERSION_H_
#define VERSION_H_

#define EE_FW_PROJECT_NAME "ci_cd_demo"
#define EE_FW_VERSION_STRING "0.1.0"
#define EE_FW_BUILD_CONFIG "Release"
#define EE_FW_BUILD_ID "ci_cd_demo-Release-20260812194819Z-9e9ff1bbb139"
#define EE_FW_GIT_SHA "9e9ff1bbb139"
#define EE_FW_BUILD_TIMESTAMP_UTC "2026-08-12T19:48:19Z"


#endif /* VERSION_H_ */

