# !/usr/bin/env python3

"""Generate version information header consumed by the firmware."""

from __future__ import annotations
from datetime import datetime, timezone
from pathlib import Path
import argparse
import subprocess


DEFAULT_PROJECT = "ci_cd_demo"
DEFAULT_VERSION = "0.1.0"
DEFAULT_CONFIG = "Release"

# parents[0] = /Users/user/Developer/embedded/stm32/CI_CD/scripts
# parents[1] = /Users/user/Developer/embedded/stm32/CI_CD
def repo_root() -> Path:
    """Get the root directory of the repository."""
    return Path(__file__).resolve().parents[1]


def get_git_commit_hash(root: Path) -> str:
    """Get the current short git commit hash/SHA."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            check=True, #We expect error to be raised hence we set it to True
            cwd=root, #Set the working directory for the subprocess
            capture_output=True, #We want to capture the output of the command
            text=True #We want the output to be returned as a string rather than bytes

        )
        return result.stdout.strip() or "nogit"
    
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "nogit"

def gen_version_header(
        *, #enforces that all following parameters must be specified as keyword arguments
        project:str,
        version:str,
        config:str,
        git_sha:str,
        timestamp_utc:str,
        build_id:str

        )->str:  

    return f"""
/*
 * @file version.h
 *
 * @brief Auto generated identity macros. 
 * This file is generated by scripts/gen_version.py and should not be modified manually. 
 * Manual edits will be overwritten by the next build.
 */

#ifndef VERSION_H_
#define VERSION_H_

#define EE_FW_PROJECT_NAME "{project}"
#define EE_FW_VERSION_STRING "{version}"
#define EE_FW_BUILD_CONFIG "{config}"
#define EE_FW_BUILD_ID "{build_id}"
#define EE_FW_GIT_SHA "{git_sha}"
#define EE_FW_BUILD_TIMESTAMP_UTC "{timestamp_utc}"


#endif /* VERSION_H_ */

"""

def get_arguments() -> argparse.Namespace:
    """Parse argument, derive build identity fields, and write the version.h file."""
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--project", default=DEFAULT_PROJECT, help="STM32CubeIDE project folder name")
    parser.add_argument("--config", default=DEFAULT_CONFIG, help="Build configuration (e.g., Debug, Release)")
    parser.add_argument("--version", default=DEFAULT_VERSION, help="Version string (e.g., 1.0.0)")
    parser.add_argument("--output", type=Path, help="Optional override for the generated output file path (i.e., version.h)")
    return parser.parse_args()


def main() -> int:
    """Main function to generate the version header. """
    #  get command line arguments
    args = get_arguments()
    # get the root of the repository and git commit hash
    root = repo_root()
    git_sha = get_git_commit_hash(root)

    timestamp_now = datetime.now(timezone.utc)
    timestamp_utc = timestamp_now.strftime("%Y-%m-%dT%H:%M:%SZ")
    build_stamp = timestamp_now.strftime("%Y%m%d%H%M%SZ")
    build_id = f"{args.project}-{args.config}-{build_stamp}-{git_sha}"

    version_header_content = gen_version_header(
        project=args.project,
        version=args.version,
        config=args.config,
        git_sha=git_sha,
        timestamp_utc=timestamp_utc,
        build_id=build_id
    )

    output_path = args.output or root/args.project/"Inc"/"version.h"

    output_path.write_text(version_header_content)
    print(f"Generated version header at: {output_path}")

    return 0


if __name__ == "__main__":
    # Exit the script with the return code from main()
    raise SystemExit(main())
