name: First Test Action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build_Firmware:
    runs-on: ubuntu-latest # self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python 
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Print Hello message
        run: |
          echo "Hello, world! from Github Actions"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"

      - name: Show Python version
        run: python --version

      - name: Install ARM GNU Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Check ARM compiler
        run: |
          which make
          arm-none-eabi-gcc --version
          arm-none-eabi-g++ --version
          arm-none-eabi-objcopy --version
          arm-none-eabi-size --version

      - name: Create a Simple artifact
        run: |
          mkdir hello_outputs
          echo "Add other actions to build, test, and deploy your project." > hello_outputs/output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: hello-actions-outputs
          path: hello_outputs/output.txt

      - name: Run Build script
        run: |
          echo "Running the build scripts..."
          python3  ${{ github.workspace }}/scripts/build_firmware.py --cubeide no
      
      # We are bundling the built files together for later use
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ci-cd-demo-build-files
          path: |
            ci_cd_demo/CI_Release/build/ci_cd_demo.elf
            ci_cd_demo/CI_Release/build/ci_cd_demo.map
            ci_cd_demo/CI_Release/build/ci_cd_demo.list
            out/logs/build.log